language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf libtool-bin
script:
  - ./build.sh
  - ./build.sh test
