# This is a basic workflow to help you get started with Actions

name: Build & Test on Ubuntu

on: 
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/mingw-w64.yml'
      - '.github/workflows/macos.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/mingw-w64.yml'
      - '.github/workflows/macos.yml'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4

    - name: intall apt packages
      run: sudo apt-get -qq install pkg-config rake bison libtool-bin libncurses5-dev libncursesw5-dev
    - name: set env
      run: echo "TERM=xterm" >> $GITHUB_ENV
    - name: build
      run: ./build.sh
    - name: test
      run: ./build.sh test
